# This file was generated by GoReleaser. DO NOT EDIT.
cask "gctl" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4a6ffad71bde78d3eb253ea161985d5c96b80ea1c5e2d172010cd5e251097052"
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v#{version}/gctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b38900893098e2fe2cbe5a9ccfe56ab3cccf2f18264d3f3f4a17bddfb0a3cd28"
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v#{version}/gctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3956cda25532d7b51cc8d28d1de70cbb74961531ddb1a1af869b4f72ee01ad9e"
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v#{version}/gctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "58a50eed0291c44dad3ab3841d43e6c9d7b9323fa906f245581346d2f3770c95"
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v#{version}/gctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gctl"
  desc "Gravitee CLI for APIM & AM"
  homepage "https://github.com/gravitee-io/gravitee-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gctl"]
    end
  end

  # No zap stanza required

end
