# This file was generated by GoReleaser. DO NOT EDIT.
cask "gctl-ro" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e4ab0b8953c2571aff61ceaf99e23f3da15cfed92ba1344bd0f8a47629b3aeb7"
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v#{version}/gctl_readonly_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f5670a02e54cbd34260394294953502111ac0e449c46ed582e0f5d89ffeebec6"
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v#{version}/gctl_readonly_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c927e79047548e3d820595bb8c21c8fc4fb0ac66f3ee4fa4147f18dd2af5485e"
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v#{version}/gctl_readonly_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "215659183afc3308d46840e946526336c5cefc6c5373d63c85c1da93a8ec1d83"
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v#{version}/gctl_readonly_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gctl-ro"
  desc "Gravitee CLI for APIM & AM read-only"
  homepage "https://github.com/gravitee-io/gravitee-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gctl-ro"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gctl-ro"]
    end
  end

  # No zap stanza required

end
