# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gctl < Formula
  desc "Gravitee CLI for APIM & AM"
  homepage "https://github.com/gravitee-io/gravitee-cli"
  version "0.1.0-rc3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0-rc3/gctl_0.1.0-rc3_darwin_amd64.tar.gz"
      sha256 "5256edd767ff1e1039e57feb96af5fd3e70969a02fd99cff32920be3713cd35b"

      define_method(:install) do
        bin.install "gctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0-rc3/gctl_0.1.0-rc3_darwin_arm64.tar.gz"
      sha256 "7b598458a0d121625b1a8d4698477d8091191a9218d4ba145a9dfa0df1c99900"

      define_method(:install) do
        bin.install "gctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0-rc3/gctl_0.1.0-rc3_linux_amd64.tar.gz"
      sha256 "6cb482d28d76bda6fdf57c8630132f4085f26af91ce6add2655539e1bfb92795"
      define_method(:install) do
        bin.install "gctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0-rc3/gctl_0.1.0-rc3_linux_arm64.tar.gz"
      sha256 "9f634489cb6072ba026ce4b2d8acaa251a8265812ce4a303b46941c4f7cf2c4d"
      define_method(:install) do
        bin.install "gctl"
      end
    end
  end

  test do
    system "#{bin}/gctl", "version"
  end
end
