# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gctl < Formula
  desc "Gravitee CLI for APIM & AM"
  homepage "https://github.com/gravitee-io/gravitee-cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0/gctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "bc2d24195ffc7174de4a536caed93aef632cddd9f84a2764a95167e6d7ba1080"

      define_method(:install) do
        bin.install "gctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0/gctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "74fd4d2bb7df26b2291e0740d30c1099ef24b792599526670e53abea72a4b16b"

      define_method(:install) do
        bin.install "gctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0/gctl_0.1.0_linux_amd64.tar.gz"
      sha256 "6454bedda3d4c54bede23fbd1f2329f094cf430b5a7190e97e5822d09dd7103d"
      define_method(:install) do
        bin.install "gctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0/gctl_0.1.0_linux_arm64.tar.gz"
      sha256 "f1d2e8370ca79071c4a328b307310ebb7f4873b9f07ad9615c3fd628f94c51f3"
      define_method(:install) do
        bin.install "gctl"
      end
    end
  end

  test do
    system "#{bin}/gctl", "version"
  end
end
