# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GctlRo < Formula
  desc "Gravitee CLI for APIM & AM read-only"
  homepage "https://github.com/gravitee-io/gravitee-cli"
  version "0.1.0-rc3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0-rc3/gctl_readonly_0.1.0-rc3_darwin_amd64.tar.gz"
      sha256 "ecedf41844b0de0d893c055ea0203e1b20b7672c180d1098aafb8171f22a6396"

      define_method(:install) do
        bin.install "gctl-ro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0-rc3/gctl_readonly_0.1.0-rc3_darwin_arm64.tar.gz"
      sha256 "d6c5d3873f809d93fc86dfad6f59d5f170f87f597166cd7bc434f9f87fcd2c57"

      define_method(:install) do
        bin.install "gctl-ro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0-rc3/gctl_readonly_0.1.0-rc3_linux_amd64.tar.gz"
      sha256 "bdeeef09938091e02353a09cc50c1bb01b1a24cf8aaa87f5c68c8b3af1718aac"
      define_method(:install) do
        bin.install "gctl-ro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io/gravitee-cli/releases/download/v0.1.0-rc3/gctl_readonly_0.1.0-rc3_linux_arm64.tar.gz"
      sha256 "807dd1da70fb967b1711da2a082d660ce482dcdfd6fc96f29f6ef1d483861825"
      define_method(:install) do
        bin.install "gctl-ro"
      end
    end
  end

  test do
    system "#{bin}/gctl-ro", "version"
  end
end
